### ISSUE TITLE
Preparing editable metadata (pyproject.toml) ... error

### ISSUE THREAD

**Issue by PabloMarhoff** [automl/PFNs#2]
I'm encountering an error during the installation of the package.
Error message:
```
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
```
**Cause:**
The issue seems to be a result of an update in the Hatchling package.

**Workaround:**
A temporary workaround is to use Hatchling version 1.18.0. This can be achieved by adding the following line to the pyproject.toml file:
```
[build-system]
requires = ["hatchling==1.18.0"]
```

The error appears both on my system (Python 3.9.16, Ubuntu 22.04.3 LTS) and trying to run the Getting Started Notebook on Colab.

**Comment by SamuelGabriel** [comment]
thanks for opening this and giving the quick fix. I don't really understand what hatchling does not like about our pyproject, and used your quick fix to fix: so it is fixed now :)

Thanks again!
