### ISSUE TITLE
activation choice bug in simple MLP prior

### ISSUE THREAD

**Issue by doronator** [automl/PFNs#5]
the design clearly is meant to allow choosing amongst various activations:
https://github.com/automl/PFNs/blob/main/pfns/priors/simple_mlp.py#L29

But the simple MLP ends up always using tanh in the forward pass:
https://github.com/automl/PFNs/blob/main/pfns/priors/simple_mlp.py#L57

the fix is simply to replace:
x = torch.tanh(x)
with:
x = self.activation(x)

**Comment by SamuelGabriel** [comment]
good catch! I will fix that in a minute.

**Comment by SamuelGabriel** [comment]
just tested, is fixed now :)
