### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by sesmeis** [automl/PFNs#6]
Hi,

I was trying to run the Getting_Started_With_PFNs notebook but encountered the error
"TypeError: issubclass() arg 1 must be a class"
when trying to train the model.

Thank you!

**Comment by SamuelGabriel** [comment]
could you please provide the whole stack trace?

**Comment by SamuelGabriel** [comment]
Sorry for this bug.... It is fixed now!
